<?php
declare(strict_types=1);
session_start(); require_once __DIR__ . '/../lib/bootstrap.php';
$error='';
if(isset($_POST['logout'])){session_destroy();header('Location: index.php');exit;}
if(isset($_POST['password'])){ $hash=(string)(config()['ADMIN_PASSWORD_HASH']??''); if($hash!==''&&password_verify((string)$_POST['password'],$hash)){session_regenerate_id(true);$_SESSION['admin']=true;}else $error='Đăng nhập không hợp lệ.'; }
if(empty($_SESSION['admin'])){ ?><!doctype html><meta charset="utf-8"><title>Backup Admin</title><form method="post"><h1>Backup Admin</h1><input type="password" name="password" required autocomplete="current-password"><button>Đăng nhập</button><p><?=htmlspecialchars($error)?></p></form><?php exit; }
$pdo=db(); $counts=$pdo->query("SELECT region,COUNT(*) total FROM lottery_draws GROUP BY region")->fetchAll(); $health=$pdo->query("SELECT source,success_count,failure_count,average_response_time,last_success,last_failure,updated_at FROM source_health ORDER BY updated_at DESC")->fetchAll(); $sync=$pdo->query("SELECT status,COUNT(*) total FROM sync_logs GROUP BY status")->fetchAll(); $lastSync=$pdo->query("SELECT MAX(created_at) FROM sync_logs WHERE status='success'")->fetchColumn(); $lastData=$pdo->query("SELECT MAX(draw_date) FROM lottery_draws")->fetchColumn();
?><!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>InfinityFree Backup</title><style>body{font:15px system-ui;max-width:1100px;margin:auto;padding:24px;background:#f5f7fb;color:#172033}section{background:white;padding:18px;margin:14px 0;border-radius:12px}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}.ok{color:#08783e}button{padding:9px 14px}</style><h1>Lottery Backup Dashboard</h1><section><b class="ok">SERVER ONLINE</b> · <b class="ok">DATABASE ONLINE</b><p>LAST SYNC: <?=htmlspecialchars((string)$lastSync)?> · LAST SUCCESSFUL DATA: <?=htmlspecialchars((string)$lastData)?></p><?php foreach($counts as $row): ?><b><?=htmlspecialchars($row['region'])?>:</b> <?=intval($row['total'])?> draws &nbsp;<?php endforeach; ?></section><section><h2>Source health</h2><table><tr><th>Source</th><th>Status</th><th>Latency</th><th>Success</th><th>Failures</th><th>Last update</th></tr><?php foreach($health as $row):?><tr><td><?=htmlspecialchars($row['source'])?></td><td><?=strtotime((string)$row['last_success'])>=strtotime((string)$row['last_failure'])?'Online':'Unhealthy'?></td><td><?=htmlspecialchars($row['average_response_time'])?> ms</td><td><?=intval($row['success_count'])?></td><td><?=intval($row['failure_count'])?></td><td><?=htmlspecialchars($row['updated_at'])?></td></tr><?php endforeach;?></table></section><section><h2>Sync</h2><?php foreach($sync as $row):?><b><?=htmlspecialchars($row['status'])?>:</b> <?=intval($row['total'])?> &nbsp;<?php endforeach;?><p><button onclick="location.reload()">Check System</button> <button type="button" onclick="alert('Gọi POST /api/admin/backfill trên primary bằng tài khoản quản trị để chỉ đồng bộ khoảng ngày thiếu.')">Sync Missing Data</button></p></section><form method="post"><button name="logout">Đăng xuất</button></form></html>
