#!/usr/bin/env python3
"""
proxy-rotate.py — Docker sidecar for proxy-pool + 9Router

Runs inside a Python container. Periodically:
1. Queries proxy-pool API for the best verified proxy.
2. Writes the proxy URL to /9router-data/proxy.env for 9Router.
3. Restarts 9Router container if Docker socket is available.

Env vars: PROXY_POOL_URL, ROTATE_INTERVAL, MIN_SCORE,
          PROTOCOL_FILTER (http|socks5|any), PROXY_OUTPUT_FILE.
"""

import os, sys, time, json, logging
import urllib.request, urllib.error
from datetime import datetime, timezone

PROXY_POOL_URL = os.environ.get("PROXY_POOL_URL", "http://proxy-pool:5000")
ROTATE_INTERVAL = int(os.environ.get("ROTATE_INTERVAL", "300"))
MIN_SCORE = float(os.environ.get("MIN_SCORE", "50"))
PROTOCOL_FILTER = os.environ.get("PROTOCOL_FILTER", "http").lower()
PROXY_OUTPUT_FILE = os.environ.get("PROXY_OUTPUT_FILE", "/9router-data/proxy.env")
CONTAINER = os.environ.get("NINE_ROUTER_CONTAINER", "9router")

logging.basicConfig(level=logging.INFO,
    format="%(asctime)s [proxy-rotate] %(levelname)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S")
log = logging.getLogger("proxy-rotate")



def fetch_best_proxy() -> dict | None:
    """Query proxy-pool API and return the best matching proxy item."""
    params = {"limit": "20", "min_score": str(MIN_SCORE), "anonymous": "true"}
    if PROTOCOL_FILTER in ("http", "socks5"):
        params["source_protocol"] = PROTOCOL_FILTER
    query = "&".join(f"{k}={v}" for k, v in params.items())
    url = f"{PROXY_POOL_URL}/proxies?{query}"
    try:
        req = urllib.request.Request(url, headers={"Accept": "application/json"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode()).get("items", [None])[0]
    except Exception as exc:
        log.warning("Failed to fetch proxies: %s", exc)
        return None


def build_proxy_url(item: dict) -> str:
    ep = item["endpoint"]
    proto = item.get("source_protocol", "http")
    if proto in ("socks5", "socks4"):
        return f"socks5://{ep}"
    return f"http://{ep}"


def write_proxy_env(proxy_url: str):
    os.makedirs(os.path.dirname(PROXY_OUTPUT_FILE), exist_ok=True)
    ts = datetime.now(timezone.utc).isoformat()
    content = (
        f"# Auto-generated by proxy-rotate at {ts}\n"
        f"HTTP_PROXY={proxy_url}\n"
        f"HTTPS_PROXY={proxy_url}\n"
        f"ALL_PROXY={proxy_url}\n"
        f"NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16\n"
    )
    tmp = PROXY_OUTPUT_FILE + ".tmp"
    with open(tmp, "w") as f:
        f.write(content)
    os.replace(tmp, PROXY_OUTPUT_FILE)
    log.info("Wrote proxy config: %s", proxy_url)


def restart_9router():
    try:
        import subprocess
        r = subprocess.run(["docker", "restart", CONTAINER],
                           capture_output=True, text=True, timeout=30)
        if r.returncode == 0:
            log.info("Restarted 9Router container")
        else:
            log.warning("docker restart failed: %s", r.stderr.strip())
    except FileNotFoundError:
        log.info("Docker CLI not available — restart 9Router manually")
    except Exception as exc:
        log.warning("Could not restart 9Router: %s", exc)


def verify_proxy(proxy_url: str) -> bool:
    if proxy_url.startswith("socks5://"):
        log.info("Skipping SOCKS5 verification (trust pool)")
        return True
    try:
        handler = urllib.request.ProxyHandler({"http": proxy_url, "https": proxy_url})
        opener = urllib.request.build_opener(handler)
        req = urllib.request.Request("https://api.ipify.org?format=json",
                                     headers={"User-Agent": "proxy-rotate/1.0"})
        with opener.open(req, timeout=10) as resp:
            body = json.loads(resp.read().decode())
            log.info("Proxy verified — exit IP: %s", body.get("ip", "?"))
            return True
    except Exception as exc:
        log.warning("Proxy verification failed: %s", exc)
        return False


def main():
    log.info("Starting rotation (interval=%ds, pool=%s)", ROTATE_INTERVAL, PROXY_POOL_URL)
    last = None
    while True:
        try:
            item = fetch_best_proxy()
            if item is None:
                time.sleep(ROTATE_INTERVAL)
                continue
            url = build_proxy_url(item)
            score = item.get("quality", {}).get("score", "?")
            if url == last:
                log.info("Same proxy (%s, score=%s), skipping", url, score)
                time.sleep(ROTATE_INTERVAL)
                continue
            log.info("New best: %s (score=%s)", url, score)
            if verify_proxy(url):
                write_proxy_env(url)
                restart_9router()
                last = url
        except Exception as exc:
            log.error("Rotation error: %s", exc, exc_info=True)
        time.sleep(ROTATE_INTERVAL)


if __name__ == "__main__":
    main()
